// Code generated by "stringer -type=xpGain -linecomment"; DO NOT EDIT.

package structs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[xpGainS-0]
	_ = x[xpGainM-1]
	_ = x[xpGainL-2]
}

const _xpGain_name = "SML"

var _xpGain_index = [...]uint8{0, 1, 2, 3}

func (i xpGain) String() string {
	if i < 0 || i >= xpGain(len(_xpGain_index)-1) {
		return "xpGain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _xpGain_name[_xpGain_index[i]:_xpGain_index[i+1]]
}
